IMPORT LIBRARIES

In [1]:
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

LOAD DATASET

In [2]:
df = pd.read_csv("student_dataset.csv")
df

    study_hours  attendance  previous_score result
0             2          60              45   Fail
1             3          70              50   Fail
2             4          75              55   Pass
3             5          80              60   Pass
4             1          50              35   Fail
5             6          90              75   Pass
6             7          95              80   Pass
7             3          65              48   Fail
8             8          98              85   Pass
9             2          55              40   Fail
10            5          85              70   Pass
11            4          78              58   Pass
12            6          88              72   Pass
13            1          45              30   Fail
14            7          92              82   Pass
15            2          58              42   Fail
16            5          82              68   Pass
17            6          87              74   Pass
18            3          68              52   Fail
19            8          97              88   Pass
20            4          76              57   Pass
21            2          53              39   Fail
22            7          93              81   Pass
23            5          84              69   Pass
24            1          48              32   Fail
25            6          89              73   Pass
26            3          66              49   Fail
27            8          99              90   Pass
28            4          79              59   Pass
29            2          57              41   Fail

EXPLORING DATASET

In [3]:
df.head()

   study_hours  attendance  previous_score result
0            2          60              45   Fail
1            3          70              50   Fail
2            4          75              55   Pass
3            5          80              60   Pass
4            1          50              35   Fail

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   study_hours     30 non-null     int64
 1   attendance      30 non-null     int64
 2   previous_score  30 non-null     int64
 3   result          30 non-null     object
dtypes: int64(3), object(1)
memory usage: 1.1+ KB

In [5]:
df.shape

(30, 4)

In [6]:
df.isnull().sum()

study_hours       0
attendance        0
previous_score    0
result            0
dtype: int64

In [7]:
df.describe()

       study_hours  attendance  previous_score
count    30.000000   30.000000       30.000000
mean      4.333333   75.400000       59.966667
std       2.218004   16.445521       17.754035
min       1.000000   45.000000       30.000000
25%       2.250000   61.250000       45.750000
50%       4.000000   78.500000       58.500000
75%       6.000000   88.750000       73.750000
max       8.000000   99.000000       90.000000

PREPROCESSING DATA

In [15]:
encoder = LabelEncoder()
df["result"] = encoder.fit_transform(df["result"])
print("\nENCODED DATASET")
print(df.head())

ENCODED DATASET
   study_hours  attendance  previous_score  result
0            2          60              45       0
1            3          70              50       0
2            4          75              55       1
3            5          80              60       1
4            1          50              35       0

In [16]:
X = df[["study_hours","attendance","previous_score"]]
X

    study_hours  attendance  previous_score
0             2          60              45
1             3          70              50
2             4          75              55
3             5          80              60
4             1          50              35
5             6          90              75
6             7          95              80
7             3          65              48
8             8          98              85
9             2          55              40
10            5          85              70
11            4          78              58
12            6          88              72
13            1          45              30
14            7          92              82
15            2          58              42
16            5          82              68
17            6          87              74
18            3          68              52
19            8          97              88
20            4          76              57
21            2          53              39
22            7          93              81
23            5          84              69
24            1          48              32
25            6          89              73
26            3          66              49
27            8          99              90
28            4          79              59
29            2          57              41

In [18]:
y = df["result"]
y

0     0
1     0
2     1
3     1
4     0
5     1
6     1
7     0
8     1
9     0
10    1
11    1
12    1
13    0
14    1
15    0
16    1
17    1
18    0
19    1
20    1
21    0
22    1
23    1
24    0
25    1
26    0
27    1
28    1
29    0
Name: result, dtype: int64

In [19]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [20]:
model = LogisticRegression()
model.fit(X_train,y_train)

LogisticRegression()

In [21]:
y_pred = model.predict(X_test)

In [ ]:
Accuracy = accuracy_score(y_test,y_pred)
Accuracy

1.0

In [23]:
Confusion_Matrix = confusion_matrix(y_test,y_pred)
Confusion_Matrix

array([[2, 0],
       [0, 4]])

In [29]:
print(classification_report(y_test,y_pred))
print("\nCLASSIFICATION REPORT")

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         2
           1       1.00      1.00      1.00         4

    accuracy                           1.00         6
   macro avg       1.00      1.00      1.00         6
weighted avg       1.00      1.00      1.00         6


CLASSIFICATION REPORT

In [30]:
study_hours = float(input("\nEnter Study Hours: "))
attendance = float(input("Enter Attendance Percentage: "))
previous_score = float(input("Enter Previous Score: "))

new_student = [[study_hours,attendance,previous_score]]

prediction = model.predict(new_student)
if prediction[0] == 1:
    print("\nPrediction: PASS")
else:
    print("\nPrediction: FAIL")

Prediction: PASS

c:\Users\aipa_\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(